services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

build:
  image: docker:stable
  stage: build
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

rspec:
  image:
    name: $DOCKER_IMAGE
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  stage: test
  script:
    - cd /examine/ && bundle exec rspec

examine:
  image:
    name: docker:stable
  allow_failure: true
  variables:
    CLAIR_URL: http://docker:6060
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    GIT_STRATEGY: none
    NO_PROXY: docker,localhost
  stage: test
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker run -v /var/run/docker.sock:/var/run/docker.sock $DOCKER_IMAGE clair scan mokhan/minbox:latest --clair_url $CLAIR_URL --ip $(hostname -i)

examine-it:
  image:
    name: docker:stable
  allow_failure: true
  variables:
    CLAIR_URL: http://docker:6060
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    GIT_STRATEGY: none
    NO_PROXY: docker,localhost
  stage: test
  script:
    - apk add ruby curl
    - gem install bundler -v '~> 2.0' --no-document
    - gem install examine
    - examine clair scan mokhan/minbox:latest --clair_url $CLAIR_URL --ip $(hostname -i)
