services:
  - docker:stable-dind

stages:
  - build
  - test

include:
  - template: Container-Scanning.gitlab-ci.yml

build:
  image: docker:stable
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE

rspec:
  image:
    name: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  stage: test
  script:
    - pwd
    - ls -alh
    - ls -alh /
    - bundle exec rspec

examine:
  image:
    name: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
  stage: test
  script:
    - clair scan mokhan/minbox:latest
